# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.cache/wt [current_project]
set_property parent.project_path C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.srcs/sources_1/ip/rom_chars/rom_chars.xci
set_property is_locked true [get_files C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.srcs/sources_1/ip/rom_chars/rom_chars.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1 -new_name rom_chars -ip [get_ips rom_chars]]

if { $cached_ip eq {} } {

synth_design -top rom_chars -part xc7a35tcpg236-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix rom_chars_ rom_chars.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ rom_chars_stub.v
 lappend ipCachedFiles rom_chars_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ rom_chars_stub.vhdl
 lappend ipCachedFiles rom_chars_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ rom_chars_sim_netlist.v
 lappend ipCachedFiles rom_chars_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ rom_chars_sim_netlist.vhdl
 lappend ipCachedFiles rom_chars_sim_netlist.vhdl

 config_ip_cache -add -dcp rom_chars.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips rom_chars]
}

rename_ref -prefix_all rom_chars_

write_checkpoint -force -noxdef rom_chars.dcp

catch { report_utilization -file rom_chars_utilization_synth.rpt -pb rom_chars_utilization_synth.pb }

if { [catch {
  write_verilog -force -mode synth_stub C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


}; # end if cached_ip 

add_files C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars_stub.v -of_objects [get_files C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.srcs/sources_1/ip/rom_chars/rom_chars.xci]

add_files C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars_stub.vhdl -of_objects [get_files C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.srcs/sources_1/ip/rom_chars/rom_chars.xci]

add_files C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars_sim_netlist.v -of_objects [get_files C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.srcs/sources_1/ip/rom_chars/rom_chars.xci]

add_files C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars_sim_netlist.vhdl -of_objects [get_files C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.srcs/sources_1/ip/rom_chars/rom_chars.xci]

add_files C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars.dcp -of_objects [get_files C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.srcs/sources_1/ip/rom_chars/rom_chars.xci]

if {[file isdir C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.ip_user_files/ip/rom_chars]} {
  catch { 
    file copy -force C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars_sim_netlist.v C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.ip_user_files/ip/rom_chars
  }
}

if {[file isdir C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.ip_user_files/ip/rom_chars]} {
  catch { 
    file copy -force C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars_sim_netlist.vhdl C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.ip_user_files/ip/rom_chars
  }
}

if {[file isdir C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.ip_user_files/ip/rom_chars]} {
  catch { 
    file copy -force C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars_stub.v C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.ip_user_files/ip/rom_chars
  }
}

if {[file isdir C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.ip_user_files/ip/rom_chars]} {
  catch { 
    file copy -force C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.runs/rom_chars_synth_1/rom_chars_stub.vhdl C:/Users/Luke/Documents/EGR426/Project02_all_together/theseus.ip_user_files/ip/rom_chars
  }
}
