# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.cache/wt [current_project]
set_property parent.project_path C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Luke/Documents/EGR426/Project03_cpu/testfile.coe
add_files -quiet C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/ip/cpuram/cpuram.dcp
set_property used_in_implementation false [get_files C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/ip/cpuram/cpuram.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/new/microram_sim.vhd
  C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/new/alu.vhd
  C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/new/cpu.vhd
  C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/new/seg_mux.vhd
  C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/new/clk_div.vhd
  C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/new/top_level.vhd
  C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/new/microram.vhd
  C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/new/microram_sim_inc.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/constrs_1/new/cpu_pins.xdc
set_property used_in_implementation false [get_files C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/constrs_1/new/cpu_pins.xdc]


synth_design -top top_level -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top_level.dcp

catch { report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb }
