# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/theseus_rom/theseus_rom.xci
# IP: The module: 'theseus_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/theseus_rom/theseus_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'theseus_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/theseus_rom/theseus_rom.xci
# IP: The module: 'theseus_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/theseus_rom/theseus_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'theseus_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
