# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.cache/wt [current_project]
set_property parent.project_path C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_ip -quiet c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/theseus_rom/theseus_rom.xci
set_property is_locked true [get_files c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/theseus_rom/theseus_rom.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top theseus_rom -part xc7a35tcpg236-1 -mode out_of_context

rename_ref -prefix_all theseus_rom_

write_checkpoint -force -noxdef theseus_rom.dcp

catch { report_utilization -file theseus_rom_utilization_synth.rpt -pb theseus_rom_utilization_synth.pb }

if { [catch {
  write_verilog -force -mode synth_stub C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

add_files C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom_stub.v -of_objects [get_files c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/theseus_rom/theseus_rom.xci]

add_files C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom_stub.vhdl -of_objects [get_files c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/theseus_rom/theseus_rom.xci]

add_files C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom_sim_netlist.v -of_objects [get_files c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/theseus_rom/theseus_rom.xci]

add_files C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom_sim_netlist.vhdl -of_objects [get_files c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/theseus_rom/theseus_rom.xci]

add_files C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom.dcp -of_objects [get_files c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/theseus_rom/theseus_rom.xci]

if {[file isdir C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.ip_user_files/ip/theseus_rom]} {
  catch { 
    file copy -force C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom_sim_netlist.v C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.ip_user_files/ip/theseus_rom
  }
}

if {[file isdir C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.ip_user_files/ip/theseus_rom]} {
  catch { 
    file copy -force C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom_sim_netlist.vhdl C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.ip_user_files/ip/theseus_rom
  }
}

if {[file isdir C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.ip_user_files/ip/theseus_rom]} {
  catch { 
    file copy -force C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom_stub.v C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.ip_user_files/ip/theseus_rom
  }
}

if {[file isdir C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.ip_user_files/ip/theseus_rom]} {
  catch { 
    file copy -force C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.runs/theseus_rom_synth_1/theseus_rom_stub.vhdl C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.ip_user_files/ip/theseus_rom
  }
}
