# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Luke/Documents/EGR426/static_background_proj_2/static_background_proj_2.cache/wt [current_project]
set_property parent.project_path C:/Users/Luke/Documents/EGR426/static_background_proj_2/static_background_proj_2.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Luke/Documents/EGR426/static_background_proj_2/static_background_proj_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet c:/Users/Luke/Documents/EGR426/static_background_proj_2/static_background_proj_2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files c:/Users/Luke/Documents/EGR426/static_background_proj_2/static_background_proj_2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/Luke/Documents/EGR426/static_background_proj_2/static_background_proj_2.srcs/sources_1/new/LFSR_Random.vhd
  C:/Users/Luke/Documents/EGR426/static_background_proj_2/static_background_proj_2.srcs/sources_1/new/colorbars.vhd
  C:/Users/Luke/Documents/EGR426/static_background_proj_2/static_background_proj_2.srcs/sources_1/new/vga_controller_640_60.vhd
  C:/Users/Luke/Documents/EGR426/static_background_proj_2/static_background_proj_2.srcs/sources_1/new/vgademo1_bars_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Luke/Documents/EGR426/static_background_proj_2/static_background_proj_2.srcs/constrs_1/new/vgatop_pins.xdc
set_property used_in_implementation false [get_files C:/Users/Luke/Documents/EGR426/static_background_proj_2/static_background_proj_2.srcs/constrs_1/new/vgatop_pins.xdc]


synth_design -top vgademo1_bars_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef vgademo1_bars_top.dcp

catch { report_utilization -file vgademo1_bars_top_utilization_synth.rpt -pb vgademo1_bars_top_utilization_synth.pb }
