# BTNU
set_property PACKAGE_PIN W5 [get_ports clk100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk100MHz]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
#set_property CLOCK_BUFFER_TYPE NONE [get_ports clk100MHz]

# BTNC
set_property PACKAGE_PIN U18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN L1 [get_ports {Outport1[7]}]
set_property PACKAGE_PIN P1 [get_ports {Outport1[6]}]
set_property PACKAGE_PIN N3 [get_ports {Outport1[5]}]
set_property PACKAGE_PIN P3 [get_ports {Outport1[4]}]
set_property PACKAGE_PIN U3 [get_ports {Outport1[3]}]
set_property PACKAGE_PIN W3 [get_ports {Outport1[2]}]
set_property PACKAGE_PIN V3 [get_ports {Outport1[1]}]
set_property PACKAGE_PIN V13 [get_ports {Outport1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport1[0]}]

set_property PACKAGE_PIN V14 [get_ports {Outport0[7]}]
set_property PACKAGE_PIN U14 [get_ports {Outport0[6]}]
set_property PACKAGE_PIN U15 [get_ports {Outport0[5]}]
set_property PACKAGE_PIN W18 [get_ports {Outport0[4]}]
set_property PACKAGE_PIN V19 [get_ports {Outport0[3]}]
set_property PACKAGE_PIN U19 [get_ports {Outport0[2]}]
set_property PACKAGE_PIN E19 [get_ports {Outport0[1]}]
set_property PACKAGE_PIN U16 [get_ports {Outport0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Outport0[0]}]

set_property PACKAGE_PIN R2 [get_ports {Inport1[7]}]
set_property PACKAGE_PIN T1 [get_ports {Inport1[6]}]
set_property PACKAGE_PIN U1 [get_ports {Inport1[5]}]
set_property PACKAGE_PIN W2 [get_ports {Inport1[4]}]
set_property PACKAGE_PIN R3 [get_ports {Inport1[3]}]
set_property PACKAGE_PIN T2 [get_ports {Inport1[2]}]
set_property PACKAGE_PIN T3 [get_ports {Inport1[1]}]
set_property PACKAGE_PIN V2 [get_ports {Inport1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport1[0]}]

set_property PACKAGE_PIN W13 [get_ports {Inport0[7]}]
set_property PACKAGE_PIN W14 [get_ports {Inport0[6]}]
set_property PACKAGE_PIN V15 [get_ports {Inport0[5]}]
set_property PACKAGE_PIN W15 [get_ports {Inport0[4]}]
set_property PACKAGE_PIN W17 [get_ports {Inport0[3]}]
set_property PACKAGE_PIN W16 [get_ports {Inport0[2]}]
set_property PACKAGE_PIN V16 [get_ports {Inport0[1]}]
set_property PACKAGE_PIN V17 [get_ports {Inport0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Inport0[0]}]


# Set 7-Segment Display
set_property PACKAGE_PIN W7 [get_ports {seven_seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[6]}]

set_property PACKAGE_PIN W6 [get_ports {seven_seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[5]}]

set_property PACKAGE_PIN U8 [get_ports {seven_seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[4]}]

set_property PACKAGE_PIN V8 [get_ports {seven_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[3]}]

set_property PACKAGE_PIN U5 [get_ports {seven_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[2]}]

set_property PACKAGE_PIN V5 [get_ports {seven_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[1]}]

set_property PACKAGE_PIN U7 [get_ports {seven_seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seven_seg[0]}]

set_property PACKAGE_PIN U2 [get_ports {digit_seg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_seg[0]}]

set_property PACKAGE_PIN U4 [get_ports {digit_seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_seg[1]}]

set_property PACKAGE_PIN V4 [get_ports {digit_seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_seg[2]}]

set_property PACKAGE_PIN W4 [get_ports {digit_seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_seg[3]}]
