# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/ip/cpuram/cpuram.xci
# IP: The module: 'cpuram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/ip/cpuram/cpuram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpuram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/ip/cpuram/cpuram.xci
# IP: The module: 'cpuram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luke/Documents/EGR426/Project03_cpu/cpu.srcs/sources_1/ip/cpuram/cpuram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpuram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
