# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Luke/Documents/EGR426/LA04/LA04.srcs/sources_1/ip/four_bit_count/four_bit_count.xci
# IP: The module: 'four_bit_count' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luke/Documents/EGR426/LA04/LA04.srcs/sources_1/ip/four_bit_count/four_bit_count_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'four_bit_count'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Luke/Documents/EGR426/LA04/LA04.srcs/sources_1/ip/four_bit_count/four_bit_count.xci
# IP: The module: 'four_bit_count' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luke/Documents/EGR426/LA04/LA04.srcs/sources_1/ip/four_bit_count/four_bit_count_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'four_bit_count'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
