# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ganzevol/Debug/Debug.srcs/sources_1/ip/ila_led/ila_led.xci
# IP: The module: 'ila_led' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ganzevol/Debug/Debug.srcs/sources_1/ip/ila_led/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/ganzevol/Debug/Debug.srcs/sources_1/ip/ila_led/ila_led_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/ganzevol/Debug/Debug.srcs/sources_1/ip/ila_led/ila_led.xci
# IP: The module: 'ila_led' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ganzevol/Debug/Debug.srcs/sources_1/ip/ila_led/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/ganzevol/Debug/Debug.srcs/sources_1/ip/ila_led/ila_led_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
