webtalk_init -webtalk_dir C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Mar 19 21:54:11 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2016.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1682563" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d92ef0e5-aa96-4ea3-9dc8-2d7fece6f8d4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8c4d35b3-70ca-4320-80ca-333b8a7534fa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2594 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key chain -value "0362D093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "01:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/Basys3/15000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/Basys3/15000000:Digilent/Basys3/15000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/Basys3/15000000:Digilent/Basys3/15000000:Digilent/Basys3/15000000:" -context "labtool\\usage"
webtalk_transmit -clientid 494193715 -regid "" -xml C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.hw/webtalk/usage_statistics_ext_labtool.xml -html C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.hw/webtalk/usage_statistics_ext_labtool.html -wdm C:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
