# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/chirag/GVSUcourses/Winter17/EGR426/Projects/Project2_Feb16/vgademo4_all/vgademo4_all.srcs/sources_1/ip/title_rom/title_rom.xci
# IP: The module: 'title_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/chirag/GVSUcourses/Winter17/EGR426/Projects/Project2_Feb16/vgademo4_all/vgademo4_all.srcs/sources_1/ip/title_rom/title_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'title_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/chirag/GVSUcourses/Winter17/EGR426/Projects/Project2_Feb16/vgademo4_all/vgademo4_all.srcs/sources_1/ip/title_rom/title_rom.xci
# IP: The module: 'title_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/chirag/GVSUcourses/Winter17/EGR426/Projects/Project2_Feb16/vgademo4_all/vgademo4_all.srcs/sources_1/ip/title_rom/title_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'title_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
