# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/map_walls/map_walls.xci
# IP: The module: 'map_walls' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/map_walls/map_walls_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'map_walls'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/map_walls/map_walls.xci
# IP: The module: 'map_walls' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luke/Documents/EGR426/Project02_all_together/vgademo4_all.srcs/sources_1/ip/map_walls/map_walls_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'map_walls'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
