# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Luke/Documents/EGR426/lab01/counter/counter.cache/wt [current_project]
set_property parent.project_path C:/Users/Luke/Documents/EGR426/lab01/counter/counter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Luke/Documents/EGR426/lab01/counter/counter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Luke/Documents/EGR426/lab01/counter/counter.srcs/sources_1/bd/counter/hdl/counter_wrapper.vhd
add_files C:/Users/Luke/Documents/EGR426/lab01/counter/counter.srcs/sources_1/bd/counter/counter.bd
set_property used_in_implementation false [get_files -all c:/Users/Luke/Documents/EGR426/lab01/counter/counter.srcs/sources_1/bd/counter/ip/counter_c_counter_binary_0_0/counter_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Luke/Documents/EGR426/lab01/counter/counter.srcs/sources_1/bd/counter/counter_ooc.xdc]
set_property is_locked true [get_files C:/Users/Luke/Documents/EGR426/lab01/counter/counter.srcs/sources_1/bd/counter/counter.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top counter_wrapper -part xc7a35tcpg236-1


write_checkpoint -force -noxdef counter_wrapper.dcp

catch { report_utilization -file counter_wrapper_utilization_synth.rpt -pb counter_wrapper_utilization_synth.pb }
