# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Luke/Documents/EGR426/LA12/LA12.srcs/sources_1/ip/La12multiplier/La12multiplier.xci
# IP: The module: 'La12multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luke/Documents/EGR426/LA12/LA12.srcs/sources_1/ip/La12multiplier/La12multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'La12multiplier'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Luke/Documents/EGR426/LA12/LA12.srcs/sources_1/ip/La12multiplier/La12multiplier.xci
# IP: The module: 'La12multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luke/Documents/EGR426/LA12/LA12.srcs/sources_1/ip/La12multiplier/La12multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'La12multiplier'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
