# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Luke/Documents/EGR426/Project01_reaction_timer/Project01_reaction_timer.cache/wt [current_project]
set_property parent.project_path C:/Users/Luke/Documents/EGR426/Project01_reaction_timer/Project01_reaction_timer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Luke/Documents/EGR426/Project01_reaction_timer/Project01_reaction_timer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Luke/Documents/EGR426/Project01_reaction_timer/Project01_reaction_timer.srcs/sources_1/new/numSelect.vhd
  C:/Users/Luke/Documents/EGR426/Project01_reaction_timer/Project01_reaction_timer.srcs/sources_1/new/double_dabble.vhd
  C:/Users/Luke/Documents/EGR426/Project01_reaction_timer/Project01_reaction_timer.srcs/sources_1/new/state_machine.vhd
  C:/Users/Luke/Documents/EGR426/Project01_reaction_timer/Project01_reaction_timer.srcs/sources_1/new/num2disp.vhd
  C:/Users/Luke/Documents/EGR426/Project01_reaction_timer/Project01_reaction_timer.srcs/sources_1/new/clk_divider.vhd
  C:/Users/Luke/Documents/EGR426/Project01_reaction_timer/Project01_reaction_timer.srcs/sources_1/new/btn_debounce.vhd
  C:/Users/Luke/Documents/EGR426/Project01_reaction_timer/Project01_reaction_timer.srcs/sources_1/new/reaction_timer.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Luke/Documents/EGR426/Project01_reaction_timer/Project01_reaction_timer.srcs/constrs_1/new/seg_pins.xdc
set_property used_in_implementation false [get_files C:/Users/Luke/Documents/EGR426/Project01_reaction_timer/Project01_reaction_timer.srcs/constrs_1/new/seg_pins.xdc]


synth_design -top reaction_timer -part xc7a35tcpg236-1


write_checkpoint -force -noxdef reaction_timer.dcp

catch { report_utilization -file reaction_timer_utilization_synth.rpt -pb reaction_timer_utilization_synth.pb }
