# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/ip/rom1kx8/rom1kx8.xci
# IP: The module: 'rom1kx8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/ip/rom1kx8/rom1kx8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom1kx8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/ip/rom1kx8/rom1kx8.xci
# IP: The module: 'rom1kx8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/ip/rom1kx8/rom1kx8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom1kx8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
