# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.cache/wt [current_project]
set_property parent.project_path C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/ip/rom1kx8/typeface.coe
add_files -quiet c:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files c:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
add_files -quiet C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/ip/rom1kx8/rom1kx8.dcp
set_property used_in_implementation false [get_files C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/ip/rom1kx8/rom1kx8.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/new/CHAR_GEN.vhd
  C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/new/vga_controller_640_60.vhd
  C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/new/MY_CHAR_DRIVER.vhd
  C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/sources_1/new/vgademo2_char_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/constrs_1/new/vgatop_pins.xdc
set_property used_in_implementation false [get_files C:/Users/Luke/Documents/EGR426/Project02_characters/vgademo2_char.srcs/constrs_1/new/vgatop_pins.xdc]


synth_design -top vgademo2_char_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef vgademo2_char_top.dcp

catch { report_utilization -file vgademo2_char_top_utilization_synth.rpt -pb vgademo2_char_top_utilization_synth.pb }
